

    export const Customerstyle = {

        input1: {bgcolor: "blue"},
        but1: {bgcolor: "#FFA048", borderRadius: "8px", gap: "10px", display: "flex", justifyContent: "center", alignItems: "center"},
        icon1: {border: "solid 1px #D9DBDD", width: "40px", height: "40px", borderRadius: "8px", display: "flex", justifyContent: "center", alignItems: "center"},
        icon2: {border: "solid 1px #D9DBDD", width: "40px", height: "40px", borderRadius: "8px", display: "flex", justifyContent: "center", alignItems: "center"},
        search1: {display: "flex", justifyContent: "flex-start", alignItems: "center", gap: "15px", bgcolor: "white", p: "10px"},
        search2: {display: "flex", justifyContent: "space-between", alignItems: "center", marginLeft: "40px", marginTop: "30px", marginRight: "35px"},
        icon3: {height: "20px", width: "20px", padding: "0px"},
        icon4: {height: "16px", width: "16px", padding: "0px"},
        topEl4: {display: "flex", justifyContent: "center", alignItems: "center"},
        topEl5: {display: "flex", justifyContent: "flex-start", alignItems: "flex-end", width: "30px", height: "30px"},
        topEl3: {display: "flex", justifyContent: "space-between", marginRight: "10px", width: "80px"},
        topEl6: {width: "32px", height: "32px", display: "flex", justifyContent: "flex-start", alignItems: "center"},
        topEl1: {display: "flex", p: "15px", justifyContent: "space-between", alignItems: "center", boxShadow: "0px 4px 12px 0px rgba(0,0,0,4%)"},
        topEl2: {color: "#02111A", fontSize: "16px", lineHeight: "22px", fontWeight: "600", font: 'Noto, Sans', marginLeft: "8px"},
        topEl7: {display: "flex", justifyContent: "flex-start", alignItems: "center", "& .MuiBadge-dot": { backgroundColor: "red", height: "18px", width: "18px"}},
        search3: {width: "480px", heigth: "40px", borderRadius: "8px", border: "solid 1px #D9DBDD", fontSize: "10px", bgcolor: "#FFFFFF", "& .MuiOutlinedInput-root": {borderRadius: "8px"}},
        search4: {width: "20px", height: "20px", color: "#4E585E"},
        icon5: {border: "solid 1px #D9DBDD", height: "32px"},
        table1: {marginLeft: "40px", marginRight: "30px"},
        table3: {bgcolor: "FFFFFF", border: "none", boxShadow: "none", maxHeight: "380px", '&::-webkit-scrollbar': { display: 'none' } },
        table2: {bgcolor: "#F0F3F6", borderBottom: "none", color: "#4E585E", fontSize: "14px", lineHeight: "20px", fontWeight: "600"},
        table5: {borderBottomColor: "#FFFFFF", border: "solid 1px #F0F3F6", borderRadius: "0px 10px 10px 0px", bgcolor: "#F0F3F6", color: "#4E585E", fontSize: "14px", lineHeight: "20px", fontWeight: "600"},
        table4: {bgcolor: "#FFFFFF"},
        cell1: {paddingRight: "60px"},
        icon6: {width: "560px", height: "61px", bgcolor: "#FFFFFF", position: "relative", left: "4px", borderRadius: "10px 0px 0px 0px"},
        cell3: {paddingLeft: "220px"},
        table6: {bgcolor: "#F0F3F6", borderBottom: "none", paddingLeft: "220px", color: "#4E585E", fontSize: "14px", lineHeight: "20px", fontWeight: "600"},
        table7: {bgcolor: "#F0F3F6", borderBottom: "none", paddingLeft: "100px", color: "#4E585E", fontSize: "14px", lineHeight: "20px", fontWeight: "600"},
        cell4: {paddingLeft: "60px"},
        table8: {bgcolor: "#F0F3F6", borderBottom: "none", color: "#4E585E", fontSize: "14px", lineHeight: "20px", fontWeight: "600", paddingLeft: "60px"},
        cell6: {paddingLeft: "60px"}, 
        page1: {display: "flex", justifyContent: "space-between", paddingTop: "130px"},
        page2: {display: "flex", justifyContent: "flex-start", alignItems: "center"},
        select: {border: "solid 1px #E5E8EB", width: "96px", height: "28px", borderRadius: "4px", margin: "10px", fontSize: "12px", lineHeight: "16px",'& .MuiSelect-icon': {},},
        text2: {color: "#4E585E", fontWeight: "400", fontSize: "12px", lineHeight: "16px"},
        pagination: {'& .MuiPaginationItem-root.Mui-selected': {backgroundColor: "white",color: "black", border: "solid 1px #1363DF", borderRadius: "4px", '& .MuiPaginationItem-icon': {color: 'green', fontSize: '1.5rem'},}}
    }