const table={
    outer:{
        backgroundColor: '#EFF2F5',
        width: '99vw',
        height: '97vh',
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    inside:{
        backgroundColor: '#FFFFFF',
        borderRadius: '15px',
        padding: '15px',
        width: '90%',
        transform: 'translate(-15px, -25px)',   
    },
    table:{
        display: 'flex', 
        alignItems: 'center', 
    },
    topsearch:{
        display: 'flex',
        alignItems: 'center',
        border: '1px solid #ccc',
        borderRadius: '5px',
        padding: '0 8px',
        width: '400px',
    },
    icons:{
        border: '1px solid #ccc', 
        borderRadius: '5px', 
        marginTop: '2px', 
        display: 'flex', 
        padding: '5px', 
        alignItems: 'center',
    },
    iconimg:{
        color: '#4E585E',
    },
    cellhead:{
        padding: '13px', 
        color: '#4E585E',
    },
    synccard:{
        backgroundColor: '#FFFFFF',
        padding: '20px 20px 15px',
        borderRadius: '10px',
        position: 'absolute',
        top: '150px', 
        left: '400px',
        zIndex: 1000,
        width: '280px',
        textAlign: 'center',
    },
    syncicon:{
        backgroundColor: '#E0F7FA',
        borderRadius: '50%',
        width: '50px',
        height: '50px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        margin: '0 auto 10px',
    },
    edit:{
        backgroundColor: '#FFFFFF',
        padding: '16px',
        borderRadius: '8px',
        left: '85%',
        position: 'absolute',
        zIndex: 500
    },
    pagination:{
        marginLeft: '630px',
        '& .MuiPaginationItem-root': {
        border: 'none',
        transition: 'border 0.3s ease', 
        },
        '& .Mui-selected': {
        border: '1px solid #1363DF',
        color: '#1363DF',
        backgroundColor: 'white',
        '&:hover': {
            backgroundColor: 'white',
        },
        borderRadius: '8px',
},
    },      
    export1:{
        backgroundColor: '#FFFFFF',
        padding:'10px',
        borderRadius: '10px',
        position: 'absolute',
        top: '150px', 
        left: '400px',
        zIndex: 1000,
        width: '280px',
        textAlign: 'center',
        boxShadow:20,
    },
    export2:{
        borderRadius: '50%',
        backgroundColor: '#FFDAD3',
        width: '40px',
        height: '40px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 'auto',
    },
    import1:{
        backgroundColor: '#FFFFFF',
        padding:'10px',
        borderRadius: '10px',
        position: 'absolute',
        top: '150px', 
        left: '330px',
        zIndex: 1000,
        width: '450px',
        textAlign: 'center',
        boxShadow:20,
    },
    import2:{
        borderRadius: '50%',
        backgroundColor: '#FFDDB8',
        width: '50px',
        height: '50px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 'auto',
        marginTop: '20px',
        '&:hover': {
          backgroundColor: '#FFDDB8',
        },
    },
    filter1:{
        backgroundColor: '#FFFFFF',
        padding:'15px',
        borderRadius: '10px',
        position: 'absolute',
        top: '50px', 
        left: '330px',
        zIndex: 1000,
        width: '450px',
        boxShadow:20,
    },
};

export default table;